version: "3.7"
services:
  golang_ecs_mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: golang_ecs
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

volumes:
  data:
